name: 2021-gsh
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.8
    - pip
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyter
    - jupyterlab
    - xarray
    - cartopy
    - netcdf4
    - pygmt
    - pyproj
    # To serve slides
    - livereload
    # Fatiando packages
    - pooch==1.3.0
    - verde==1.6.1
    - boule==0.2.0
    - harmonica==0.2.1
    # To speed up Verde
    - pykdtree
    - numba
